name: CI
on:
  push:
    branches: [ main ]
jobs:
  deploy-chat-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          repository:  rosebilag/chat-backend
          ref: master
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }} 
        run: heroku container:login
      - name: "Add remote"
        shell: "bash"
        run: |
          heroku git:remote --app ${{ secrets.HEROKU_APP_NAME }}
      - name: "Push to heroku"
        shell: "bash"
        run: |
          git push heroku HEAD:master
